name: CI Tests
on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   name: Install dependencies
                run: |
                    cd src
                    npm ci
    lint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install modules
                run: yarn
            -   name: Run ESLint
                run: eslint . --ext .js
    playwrite:
        needs: setup
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            -   name: Install Playwright Browsers
                run: |
                    cd src
                    npx playwright install --with-deps
            -   name: Run Playwright tests
                run: |
                    cd src
                    npx playwright test
            -   uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: playwright-report
                    path: src/playwright-report/
                    retention-days: 30