name: CI Tests
on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16

    eslint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   uses: sibiraj-s/action-eslint@v2
                with:
                    eslint-args: '--ignore-path=.gitignore --quiet'
                    extensions: 'js,jsx,ts,tsx'
                    annotations: true
    vitest:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Install dependencies
                run: |
                    ls -la
                    cd src
                    npm ci
            -   name: Run Vitest tests
                run: |
                    cd src
                    npx vitest test
    playwrite:
        needs: setup
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            -   name: Install dependencies
                run: |
                    cd src
                    npm ci
            -   name: Install Playwright Browsers
                run: |
                    cd src
                    npx playwright install --with-deps
            -   name: Run Playwright tests
                run: |
                    npm install -D @playwright/test
                    cd src
                    npx playwright test
            -   uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: playwright-report
                    path: src/playwright-report/
                    retention-days: 30